### ISSUE TITLE
Which characters to escape?

### ISSUE THREAD

**Issue by aantix** [fulmicoton/multiregexp#8]
I have the following two strings, representing my regex's

```
"<a href=\"https://ssl.mietshop.d"
"(?:<link[^>]+components/bitrix|(?:src|href)=\"/bitrix/(?:js|templates))"
```

When I attempt to create my RegExp object, I receive the following:

```
Caused by: java.lang.IllegalArgumentException: expected '"' at position 70
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseSimpleExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseCharClassExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseComplExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseRepeatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseConcatExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseInterExp(Unknown Source)
	at dk.brics.automaton.RegExp.parseUnionExp(Unknown Source)
	at dk.brics.automaton.RegExp.<init>(Unknown Source)
```

Thoughts?

**Comment by fulmicoton** [comment]
The regular expression parser is coming from the dk.brics library. This is not within the scope of multiregexp. I reckon that `dk.brics` is quite lacking on many points, and I might in the future rewrite the regular expression compiler.

**Comment by kindkid** [comment]
public static String quote(CharSequence s) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            final char c = s.charAt(i);
            switch (c) {
                case '|':
                case '&':
                case '?':
                case '*':
                case '+':
                case '{':
                case '}':
                case ',':
                case '~':
                case '[':
                case ']':
                case '^':
                case '-':
                case '.':
                case '#':
                case '@':
                case '"':
                case '(':
                case ')':
                case '<':
                case '>':
                case '\\':
                    sb.append('\\');
                default:
                    sb.append(c);
            }
        }
        return sb.toString();
    }
